/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface VisionBoardEntry {
    progressPercentage: bigint;
    targetYear: bigint;
    category: GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
}
export interface ScheduleItem {
    timeBlock: string;
    activity: string;
}
export interface Couple {
    partner1: Principal;
    partner2: Principal;
}
export interface Task {
    description: string;
    isComplete: boolean;
}
export interface DailyPlannerEntry {
    waterIntake: bigint;
    date: bigint;
    gratitudeEntries: Array<string>;
    topTasks: Array<Task>;
    journalEntry: string;
    notes: string;
    moodEmoji: string;
    schedule: Array<ScheduleItem>;
}
export interface UserProfile {
    displayName: string;
    name: string;
}
export enum GoalCategory {
    relationship = "relationship",
    spiritual = "spiritual",
    travel = "travel",
    personalGrowth = "personalGrowth",
    career = "career",
    financial = "financial",
    health = "health"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addDailyPlannerEntry(entry: DailyPlannerEntry): Promise<void>;
    addVisionBoardEntry(entry: VisionBoardEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCouple(partner1: Principal, partner2: Principal): Promise<void>;
    deleteDailyPlannerEntry(date: bigint): Promise<void>;
    deleteVisionBoardEntry(targetYear: bigint): Promise<void>;
    getAllCouples(): Promise<Array<Couple>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCouple(partner: Principal): Promise<Couple | null>;
    getDailyPlannerEntries(): Promise<Array<DailyPlannerEntry>>;
    getDailyQuote(): Promise<string>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisionBoardEntries(): Promise<Array<VisionBoardEntry>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateVisionBoardProgress(targetYear: bigint, progress: bigint): Promise<void>;
    updateWaterIntake(date: bigint, intake: bigint): Promise<void>;
}
import type { Couple as _Couple, GoalCategory as _GoalCategory, UserProfile as _UserProfile, UserRole as _UserRole, VisionBoardEntry as _VisionBoardEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addDailyPlannerEntry(arg0: DailyPlannerEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addDailyPlannerEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDailyPlannerEntry(arg0);
            return result;
        }
    }
    async addVisionBoardEntry(arg0: VisionBoardEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVisionBoardEntry(to_candid_VisionBoardEntry_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVisionBoardEntry(to_candid_VisionBoardEntry_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCouple(arg0: Principal, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCouple(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCouple(arg0, arg1);
            return result;
        }
    }
    async deleteDailyPlannerEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDailyPlannerEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDailyPlannerEntry(arg0);
            return result;
        }
    }
    async deleteVisionBoardEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVisionBoardEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVisionBoardEntry(arg0);
            return result;
        }
    }
    async getAllCouples(): Promise<Array<Couple>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCouples();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCouples();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCouple(arg0: Principal): Promise<Couple | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCouple(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCouple(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyPlannerEntries(): Promise<Array<DailyPlannerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyPlannerEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyPlannerEntries();
            return result;
        }
    }
    async getDailyQuote(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyQuote();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyQuote();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisionBoardEntries(): Promise<Array<VisionBoardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisionBoardEntries();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisionBoardEntries();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateVisionBoardProgress(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisionBoardProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisionBoardProgress(arg0, arg1);
            return result;
        }
    }
    async updateWaterIntake(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWaterIntake(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWaterIntake(arg0, arg1);
            return result;
        }
    }
}
function from_candid_GoalCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalCategory): GoalCategory {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_VisionBoardEntry_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisionBoardEntry): VisionBoardEntry {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Couple]): Couple | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    progressPercentage: bigint;
    targetYear: bigint;
    category: _GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
}): {
    progressPercentage: bigint;
    targetYear: bigint;
    category: GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
} {
    return {
        progressPercentage: value.progressPercentage,
        targetYear: value.targetYear,
        category: from_candid_GoalCategory_n14(_uploadFile, _downloadFile, value.category),
        whyThisMatters: value.whyThisMatters,
        milestones: value.milestones
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    relationship: null;
} | {
    spiritual: null;
} | {
    travel: null;
} | {
    personalGrowth: null;
} | {
    career: null;
} | {
    financial: null;
} | {
    health: null;
}): GoalCategory {
    return "relationship" in value ? GoalCategory.relationship : "spiritual" in value ? GoalCategory.spiritual : "travel" in value ? GoalCategory.travel : "personalGrowth" in value ? GoalCategory.personalGrowth : "career" in value ? GoalCategory.career : "financial" in value ? GoalCategory.financial : "health" in value ? GoalCategory.health : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VisionBoardEntry>): Array<VisionBoardEntry> {
    return value.map((x)=>from_candid_VisionBoardEntry_n12(_uploadFile, _downloadFile, x));
}
function to_candid_GoalCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): _GoalCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_VisionBoardEntry_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisionBoardEntry): _VisionBoardEntry {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    progressPercentage: bigint;
    targetYear: bigint;
    category: GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
}): {
    progressPercentage: bigint;
    targetYear: bigint;
    category: _GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
} {
    return {
        progressPercentage: value.progressPercentage,
        targetYear: value.targetYear,
        category: to_candid_GoalCategory_n3(_uploadFile, _downloadFile, value.category),
        whyThisMatters: value.whyThisMatters,
        milestones: value.milestones
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): {
    relationship: null;
} | {
    spiritual: null;
} | {
    travel: null;
} | {
    personalGrowth: null;
} | {
    career: null;
} | {
    financial: null;
} | {
    health: null;
} {
    return value == GoalCategory.relationship ? {
        relationship: null
    } : value == GoalCategory.spiritual ? {
        spiritual: null
    } : value == GoalCategory.travel ? {
        travel: null
    } : value == GoalCategory.personalGrowth ? {
        personalGrowth: null
    } : value == GoalCategory.career ? {
        career: null
    } : value == GoalCategory.financial ? {
        financial: null
    } : value == GoalCategory.health ? {
        health: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
