/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Budget {
    expenses: Array<string>;
    income: bigint;
    notes: string;
}
export interface ImportantDate {
    date: bigint;
    labelText: string;
}
export interface GrowthJournalEntry {
    growthRating: bigint;
    date: bigint;
    actionStep: string;
    lesson: string;
    isPublic: boolean;
    growthArea: GrowthArea;
}
export interface Task {
    description: string;
    isComplete: boolean;
}
export interface EmotionalJournalEntry {
    trigger: string;
    emotion: EmotionTag;
    date: bigint;
    isPublic: boolean;
    reflection: string;
    intensity: bigint;
}
export interface WeeklyEntry {
    todos: Array<Task>;
    year: bigint;
    weekNumber: bigint;
    energyRating: bigint;
    reflection: string;
    priorities: Array<Task>;
    habitTracker: Array<HabitWeekly>;
}
export interface DailyJournalEntry {
    body: string;
    date: bigint;
    isPublic: boolean;
}
export interface MonthlyEntry {
    month: bigint;
    year: bigint;
    moodTracker: Array<string>;
    goals: Array<Task>;
    importantDates: Array<ImportantDate>;
    budget: Budget;
    reflection: string;
}
export interface YearlyEntry {
    majorGoals: Array<Task>;
    year: bigint;
    reflection: string;
    habitTracker: Array<HabitYearly>;
    wordOfTheYear: string;
    visionImages: Array<string>;
}
export interface VisionBoardEntry {
    progressPercentage: bigint;
    targetYear: bigint;
    category: GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
}
export interface ScheduleItem {
    timeBlock: string;
    activity: string;
}
export interface NightReflectionJournalEntry {
    gratitude: string;
    date: bigint;
    improvements: string;
    highlights: Array<string>;
    isPublic: boolean;
    intention: string;
}
export interface Couple {
    partner1: Principal;
    partner2: Principal;
}
export interface HabitWeekly {
    name: string;
    dailyCheckIns: Array<boolean>;
}
export interface DailyPlannerEntry {
    tasks: Array<Task>;
    waterIntake: bigint;
    date: bigint;
    gratitudeEntries: Array<string>;
    journalEntry: string;
    notes: string;
    moodEmoji: string;
    schedule: Array<ScheduleItem>;
}
export interface UserProfile {
    displayName: string;
    name: string;
}
export interface HabitYearly {
    name: string;
    monthlyCheckIns: Array<boolean>;
}
export enum CoupleCreateError {
    partnerAlreadyLinked = "partnerAlreadyLinked",
    callerAlreadyLinked = "callerAlreadyLinked",
    unauthorized = "unauthorized",
    anonymousNotPermitted = "anonymousNotPermitted"
}
export enum EmotionTag {
    sad = "sad",
    fearful = "fearful",
    content = "content",
    anxious = "anxious",
    happy = "happy",
    angry = "angry",
    disappointed = "disappointed",
    calm = "calm",
    grateful = "grateful",
    peaceful = "peaceful",
    overwhelmed = "overwhelmed",
    motivated = "motivated",
    frustrated = "frustrated",
    excited = "excited",
    optimistic = "optimistic"
}
export enum GoalCategory {
    relationship = "relationship",
    spiritual = "spiritual",
    travel = "travel",
    personalGrowth = "personalGrowth",
    career = "career",
    financial = "financial",
    health = "health"
}
export enum GrowthArea {
    spiritual = "spiritual",
    other = "other",
    mindset = "mindset",
    career = "career",
    relationships = "relationships",
    health = "health"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMonthlyEntry(entry: MonthlyEntry): Promise<void>;
    addWeeklyEntry(entry: WeeklyEntry): Promise<void>;
    addYearlyEntry(entry: YearlyEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCouple(partner1: Principal, partner2: Principal): Promise<CoupleCreateError | null>;
    createOrUpdateDailyJournal(entry: DailyJournalEntry): Promise<void>;
    createOrUpdateEmotionalJournal(entry: EmotionalJournalEntry): Promise<void>;
    createOrUpdateGrowthJournal(entry: GrowthJournalEntry): Promise<void>;
    createOrUpdateNightReflection(entry: NightReflectionJournalEntry): Promise<void>;
    deleteDailyPlannerEntry(date: bigint): Promise<void>;
    deleteMonthlyEntry(year: bigint, month: bigint): Promise<void>;
    deleteVisionBoardEntry(targetYear: bigint): Promise<void>;
    deleteWeeklyEntry(year: bigint, weekNumber: bigint): Promise<void>;
    deleteYearlyEntry(year: bigint): Promise<void>;
    dissolveCouple(): Promise<boolean>;
    getAllCouples(): Promise<Array<Couple>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCouple(partner: Principal): Promise<Couple | null>;
    getDailyJournals(): Promise<Array<DailyJournalEntry>>;
    getDailyJournalsForOwner(owner: Principal): Promise<Array<DailyJournalEntry>>;
    getDailyJournalsForUser(user: Principal): Promise<Array<DailyJournalEntry>>;
    getDailyPlannerEntries(): Promise<Array<DailyPlannerEntry>>;
    getDailyQuote(dayOfYear: bigint): Promise<string>;
    getEmotionalJournals(): Promise<Array<EmotionalJournalEntry>>;
    getEmotionalJournalsForOwner(owner: Principal): Promise<Array<EmotionalJournalEntry>>;
    getGrowthJournals(): Promise<Array<GrowthJournalEntry>>;
    getGrowthJournalsForOwner(owner: Principal): Promise<Array<GrowthJournalEntry>>;
    getMonthlyEntries(): Promise<Array<MonthlyEntry>>;
    getNightReflections(): Promise<Array<NightReflectionJournalEntry>>;
    getNightReflectionsForOwner(owner: Principal): Promise<Array<NightReflectionJournalEntry>>;
    getOwnerMonthlyEntries(owner: Principal): Promise<Array<MonthlyEntry>>;
    getOwnerWeeklyEntries(owner: Principal): Promise<Array<WeeklyEntry>>;
    getOwnerYearlyEntries(owner: Principal): Promise<Array<YearlyEntry>>;
    getPartnerDailyJournals(): Promise<Array<DailyJournalEntry>>;
    getPartnerDailyPlannerEntries(): Promise<Array<DailyPlannerEntry>>;
    getPartnerDailyPlannerEntryForDate(date: bigint): Promise<DailyPlannerEntry | null>;
    getPartnerEmotionalJournals(): Promise<Array<EmotionalJournalEntry>>;
    getPartnerGrowthJournals(): Promise<Array<GrowthJournalEntry>>;
    getPartnerJournals(): Promise<{
        growth: Array<GrowthJournalEntry>;
        night: Array<NightReflectionJournalEntry>;
        emotional: Array<EmotionalJournalEntry>;
        daily: Array<DailyJournalEntry>;
    }>;
    getPartnerMonthlyEntries(): Promise<Array<MonthlyEntry>>;
    getPartnerNightReflections(): Promise<Array<NightReflectionJournalEntry>>;
    getPartnerUserProfile(): Promise<UserProfile | null>;
    getPartnerVisionBoardEntries(): Promise<Array<VisionBoardEntry>>;
    getPartnerWeeklyEntries(): Promise<Array<WeeklyEntry>>;
    getPartnerYearlyEntries(): Promise<Array<YearlyEntry>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVisionBoardEntries(): Promise<Array<VisionBoardEntry>>;
    getWeeklyEntries(): Promise<Array<WeeklyEntry>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDailyPlannerEntry(entry: DailyPlannerEntry): Promise<void>;
    saveVisionBoardEntry(entry: VisionBoardEntry): Promise<void>;
    updateMonthlyEntry(year: bigint, month: bigint, updatedEntry: MonthlyEntry): Promise<void>;
    updateVisionBoardProgress(targetYear: bigint, progress: bigint): Promise<void>;
    updateWaterIntake(date: bigint, intake: bigint): Promise<void>;
    updateWeeklyEntry(year: bigint, weekNumber: bigint, updatedEntry: WeeklyEntry): Promise<void>;
    updateYearlyEntry(year: bigint, updatedEntry: YearlyEntry): Promise<void>;
}
import type { Couple as _Couple, CoupleCreateError as _CoupleCreateError, DailyJournalEntry as _DailyJournalEntry, DailyPlannerEntry as _DailyPlannerEntry, EmotionTag as _EmotionTag, EmotionalJournalEntry as _EmotionalJournalEntry, GoalCategory as _GoalCategory, GrowthArea as _GrowthArea, GrowthJournalEntry as _GrowthJournalEntry, NightReflectionJournalEntry as _NightReflectionJournalEntry, UserProfile as _UserProfile, UserRole as _UserRole, VisionBoardEntry as _VisionBoardEntry } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMonthlyEntry(arg0: MonthlyEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMonthlyEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMonthlyEntry(arg0);
            return result;
        }
    }
    async addWeeklyEntry(arg0: WeeklyEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeeklyEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeeklyEntry(arg0);
            return result;
        }
    }
    async addYearlyEntry(arg0: YearlyEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addYearlyEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addYearlyEntry(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCouple(arg0: Principal, arg1: Principal): Promise<CoupleCreateError | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createCouple(arg0, arg1);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCouple(arg0, arg1);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrUpdateDailyJournal(arg0: DailyJournalEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateDailyJournal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateDailyJournal(arg0);
            return result;
        }
    }
    async createOrUpdateEmotionalJournal(arg0: EmotionalJournalEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateEmotionalJournal(to_candid_EmotionalJournalEntry_n6(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateEmotionalJournal(to_candid_EmotionalJournalEntry_n6(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrUpdateGrowthJournal(arg0: GrowthJournalEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateGrowthJournal(to_candid_GrowthJournalEntry_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateGrowthJournal(to_candid_GrowthJournalEntry_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createOrUpdateNightReflection(arg0: NightReflectionJournalEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateNightReflection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateNightReflection(arg0);
            return result;
        }
    }
    async deleteDailyPlannerEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDailyPlannerEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDailyPlannerEntry(arg0);
            return result;
        }
    }
    async deleteMonthlyEntry(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMonthlyEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMonthlyEntry(arg0, arg1);
            return result;
        }
    }
    async deleteVisionBoardEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVisionBoardEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVisionBoardEntry(arg0);
            return result;
        }
    }
    async deleteWeeklyEntry(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWeeklyEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWeeklyEntry(arg0, arg1);
            return result;
        }
    }
    async deleteYearlyEntry(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteYearlyEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteYearlyEntry(arg0);
            return result;
        }
    }
    async dissolveCouple(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.dissolveCouple();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dissolveCouple();
            return result;
        }
    }
    async getAllCouples(): Promise<Array<Couple>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCouples();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCouples();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCouple(arg0: Principal): Promise<Couple | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCouple(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCouple(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDailyJournals(): Promise<Array<DailyJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyJournals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyJournals();
            return result;
        }
    }
    async getDailyJournalsForOwner(arg0: Principal): Promise<Array<DailyJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyJournalsForOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyJournalsForOwner(arg0);
            return result;
        }
    }
    async getDailyJournalsForUser(arg0: Principal): Promise<Array<DailyJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyJournalsForUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyJournalsForUser(arg0);
            return result;
        }
    }
    async getDailyPlannerEntries(): Promise<Array<DailyPlannerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyPlannerEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyPlannerEntries();
            return result;
        }
    }
    async getDailyQuote(arg0: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyQuote(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyQuote(arg0);
            return result;
        }
    }
    async getEmotionalJournals(): Promise<Array<EmotionalJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmotionalJournals();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmotionalJournals();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmotionalJournalsForOwner(arg0: Principal): Promise<Array<EmotionalJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmotionalJournalsForOwner(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmotionalJournalsForOwner(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrowthJournals(): Promise<Array<GrowthJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrowthJournals();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrowthJournals();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrowthJournalsForOwner(arg0: Principal): Promise<Array<GrowthJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrowthJournalsForOwner(arg0);
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrowthJournalsForOwner(arg0);
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyEntries(): Promise<Array<MonthlyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyEntries();
            return result;
        }
    }
    async getNightReflections(): Promise<Array<NightReflectionJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNightReflections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNightReflections();
            return result;
        }
    }
    async getNightReflectionsForOwner(arg0: Principal): Promise<Array<NightReflectionJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNightReflectionsForOwner(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNightReflectionsForOwner(arg0);
            return result;
        }
    }
    async getOwnerMonthlyEntries(arg0: Principal): Promise<Array<MonthlyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerMonthlyEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerMonthlyEntries(arg0);
            return result;
        }
    }
    async getOwnerWeeklyEntries(arg0: Principal): Promise<Array<WeeklyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerWeeklyEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerWeeklyEntries(arg0);
            return result;
        }
    }
    async getOwnerYearlyEntries(arg0: Principal): Promise<Array<YearlyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOwnerYearlyEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOwnerYearlyEntries(arg0);
            return result;
        }
    }
    async getPartnerDailyJournals(): Promise<Array<DailyJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerDailyJournals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerDailyJournals();
            return result;
        }
    }
    async getPartnerDailyPlannerEntries(): Promise<Array<DailyPlannerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerDailyPlannerEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerDailyPlannerEntries();
            return result;
        }
    }
    async getPartnerDailyPlannerEntryForDate(arg0: bigint): Promise<DailyPlannerEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerDailyPlannerEntryForDate(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerDailyPlannerEntryForDate(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerEmotionalJournals(): Promise<Array<EmotionalJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerEmotionalJournals();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerEmotionalJournals();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerGrowthJournals(): Promise<Array<GrowthJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerGrowthJournals();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerGrowthJournals();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerJournals(): Promise<{
        growth: Array<GrowthJournalEntry>;
        night: Array<NightReflectionJournalEntry>;
        emotional: Array<EmotionalJournalEntry>;
        daily: Array<DailyJournalEntry>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerJournals();
                return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerJournals();
            return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerMonthlyEntries(): Promise<Array<MonthlyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerMonthlyEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerMonthlyEntries();
            return result;
        }
    }
    async getPartnerNightReflections(): Promise<Array<NightReflectionJournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerNightReflections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerNightReflections();
            return result;
        }
    }
    async getPartnerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerVisionBoardEntries(): Promise<Array<VisionBoardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerVisionBoardEntries();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerVisionBoardEntries();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPartnerWeeklyEntries(): Promise<Array<WeeklyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerWeeklyEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerWeeklyEntries();
            return result;
        }
    }
    async getPartnerYearlyEntries(): Promise<Array<YearlyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerYearlyEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerYearlyEntries();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVisionBoardEntries(): Promise<Array<VisionBoardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVisionBoardEntries();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVisionBoardEntries();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWeeklyEntries(): Promise<Array<WeeklyEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWeeklyEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWeeklyEntries();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveDailyPlannerEntry(arg0: DailyPlannerEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDailyPlannerEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDailyPlannerEntry(arg0);
            return result;
        }
    }
    async saveVisionBoardEntry(arg0: VisionBoardEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveVisionBoardEntry(to_candid_VisionBoardEntry_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveVisionBoardEntry(to_candid_VisionBoardEntry_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateMonthlyEntry(arg0: bigint, arg1: bigint, arg2: MonthlyEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMonthlyEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMonthlyEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async updateVisionBoardProgress(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateVisionBoardProgress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateVisionBoardProgress(arg0, arg1);
            return result;
        }
    }
    async updateWaterIntake(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWaterIntake(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWaterIntake(arg0, arg1);
            return result;
        }
    }
    async updateWeeklyEntry(arg0: bigint, arg1: bigint, arg2: WeeklyEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWeeklyEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWeeklyEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async updateYearlyEntry(arg0: bigint, arg1: YearlyEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateYearlyEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateYearlyEntry(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CoupleCreateError_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CoupleCreateError): CoupleCreateError {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionTag_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionTag): EmotionTag {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_EmotionalJournalEntry_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmotionalJournalEntry): EmotionalJournalEntry {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_GoalCategory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalCategory): GoalCategory {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_GrowthArea_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GrowthArea): GrowthArea {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_GrowthJournalEntry_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GrowthJournalEntry): GrowthJournalEntry {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_VisionBoardEntry_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VisionBoardEntry): VisionBoardEntry {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Couple]): Couple | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyPlannerEntry]): DailyPlannerEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CoupleCreateError]): CoupleCreateError | null {
    return value.length === 0 ? null : from_candid_CoupleCreateError_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trigger: string;
    emotion: _EmotionTag;
    date: bigint;
    isPublic: boolean;
    reflection: string;
    intensity: bigint;
}): {
    trigger: string;
    emotion: EmotionTag;
    date: bigint;
    isPublic: boolean;
    reflection: string;
    intensity: bigint;
} {
    return {
        trigger: value.trigger,
        emotion: from_candid_EmotionTag_n21(_uploadFile, _downloadFile, value.emotion),
        date: value.date,
        isPublic: value.isPublic,
        reflection: value.reflection,
        intensity: value.intensity
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    growthRating: bigint;
    date: bigint;
    actionStep: string;
    lesson: string;
    isPublic: boolean;
    growthArea: _GrowthArea;
}): {
    growthRating: bigint;
    date: bigint;
    actionStep: string;
    lesson: string;
    isPublic: boolean;
    growthArea: GrowthArea;
} {
    return {
        growthRating: value.growthRating,
        date: value.date,
        actionStep: value.actionStep,
        lesson: value.lesson,
        isPublic: value.isPublic,
        growthArea: from_candid_GrowthArea_n26(_uploadFile, _downloadFile, value.growthArea)
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    growth: Array<_GrowthJournalEntry>;
    night: Array<_NightReflectionJournalEntry>;
    emotional: Array<_EmotionalJournalEntry>;
    daily: Array<_DailyJournalEntry>;
}): {
    growth: Array<GrowthJournalEntry>;
    night: Array<NightReflectionJournalEntry>;
    emotional: Array<EmotionalJournalEntry>;
    daily: Array<DailyJournalEntry>;
} {
    return {
        growth: from_candid_vec_n23(_uploadFile, _downloadFile, value.growth),
        night: value.night,
        emotional: from_candid_vec_n18(_uploadFile, _downloadFile, value.emotional),
        daily: value.daily
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    progressPercentage: bigint;
    targetYear: bigint;
    category: _GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
}): {
    progressPercentage: bigint;
    targetYear: bigint;
    category: GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
} {
    return {
        progressPercentage: value.progressPercentage,
        targetYear: value.targetYear,
        category: from_candid_GoalCategory_n33(_uploadFile, _downloadFile, value.category),
        whyThisMatters: value.whyThisMatters,
        milestones: value.milestones
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sad: null;
} | {
    fearful: null;
} | {
    content: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    disappointed: null;
} | {
    calm: null;
} | {
    grateful: null;
} | {
    peaceful: null;
} | {
    overwhelmed: null;
} | {
    motivated: null;
} | {
    frustrated: null;
} | {
    excited: null;
} | {
    optimistic: null;
}): EmotionTag {
    return "sad" in value ? EmotionTag.sad : "fearful" in value ? EmotionTag.fearful : "content" in value ? EmotionTag.content : "anxious" in value ? EmotionTag.anxious : "happy" in value ? EmotionTag.happy : "angry" in value ? EmotionTag.angry : "disappointed" in value ? EmotionTag.disappointed : "calm" in value ? EmotionTag.calm : "grateful" in value ? EmotionTag.grateful : "peaceful" in value ? EmotionTag.peaceful : "overwhelmed" in value ? EmotionTag.overwhelmed : "motivated" in value ? EmotionTag.motivated : "frustrated" in value ? EmotionTag.frustrated : "excited" in value ? EmotionTag.excited : "optimistic" in value ? EmotionTag.optimistic : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    spiritual: null;
} | {
    other: null;
} | {
    mindset: null;
} | {
    career: null;
} | {
    relationships: null;
} | {
    health: null;
}): GrowthArea {
    return "spiritual" in value ? GrowthArea.spiritual : "other" in value ? GrowthArea.other : "mindset" in value ? GrowthArea.mindset : "career" in value ? GrowthArea.career : "relationships" in value ? GrowthArea.relationships : "health" in value ? GrowthArea.health : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    relationship: null;
} | {
    spiritual: null;
} | {
    travel: null;
} | {
    personalGrowth: null;
} | {
    career: null;
} | {
    financial: null;
} | {
    health: null;
}): GoalCategory {
    return "relationship" in value ? GoalCategory.relationship : "spiritual" in value ? GoalCategory.spiritual : "travel" in value ? GoalCategory.travel : "personalGrowth" in value ? GoalCategory.personalGrowth : "career" in value ? GoalCategory.career : "financial" in value ? GoalCategory.financial : "health" in value ? GoalCategory.health : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    partnerAlreadyLinked: null;
} | {
    callerAlreadyLinked: null;
} | {
    unauthorized: null;
} | {
    anonymousNotPermitted: null;
}): CoupleCreateError {
    return "partnerAlreadyLinked" in value ? CoupleCreateError.partnerAlreadyLinked : "callerAlreadyLinked" in value ? CoupleCreateError.callerAlreadyLinked : "unauthorized" in value ? CoupleCreateError.unauthorized : "anonymousNotPermitted" in value ? CoupleCreateError.anonymousNotPermitted : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmotionalJournalEntry>): Array<EmotionalJournalEntry> {
    return value.map((x)=>from_candid_EmotionalJournalEntry_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GrowthJournalEntry>): Array<GrowthJournalEntry> {
    return value.map((x)=>from_candid_GrowthJournalEntry_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_VisionBoardEntry>): Array<VisionBoardEntry> {
    return value.map((x)=>from_candid_VisionBoardEntry_n31(_uploadFile, _downloadFile, x));
}
function to_candid_EmotionTag_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionTag): _EmotionTag {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_EmotionalJournalEntry_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionalJournalEntry): _EmotionalJournalEntry {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_GoalCategory_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): _GoalCategory {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_GrowthArea_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GrowthArea): _GrowthArea {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_GrowthJournalEntry_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GrowthJournalEntry): _GrowthJournalEntry {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_VisionBoardEntry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: VisionBoardEntry): _VisionBoardEntry {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    growthRating: bigint;
    date: bigint;
    actionStep: string;
    lesson: string;
    isPublic: boolean;
    growthArea: GrowthArea;
}): {
    growthRating: bigint;
    date: bigint;
    actionStep: string;
    lesson: string;
    isPublic: boolean;
    growthArea: _GrowthArea;
} {
    return {
        growthRating: value.growthRating,
        date: value.date,
        actionStep: value.actionStep,
        lesson: value.lesson,
        isPublic: value.isPublic,
        growthArea: to_candid_GrowthArea_n12(_uploadFile, _downloadFile, value.growthArea)
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    progressPercentage: bigint;
    targetYear: bigint;
    category: GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
}): {
    progressPercentage: bigint;
    targetYear: bigint;
    category: _GoalCategory;
    whyThisMatters: string;
    milestones: Array<string>;
} {
    return {
        progressPercentage: value.progressPercentage,
        targetYear: value.targetYear,
        category: to_candid_GoalCategory_n37(_uploadFile, _downloadFile, value.category),
        whyThisMatters: value.whyThisMatters,
        milestones: value.milestones
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    trigger: string;
    emotion: EmotionTag;
    date: bigint;
    isPublic: boolean;
    reflection: string;
    intensity: bigint;
}): {
    trigger: string;
    emotion: _EmotionTag;
    date: bigint;
    isPublic: boolean;
    reflection: string;
    intensity: bigint;
} {
    return {
        trigger: value.trigger,
        emotion: to_candid_EmotionTag_n8(_uploadFile, _downloadFile, value.emotion),
        date: value.date,
        isPublic: value.isPublic,
        reflection: value.reflection,
        intensity: value.intensity
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GrowthArea): {
    spiritual: null;
} | {
    other: null;
} | {
    mindset: null;
} | {
    career: null;
} | {
    relationships: null;
} | {
    health: null;
} {
    return value == GrowthArea.spiritual ? {
        spiritual: null
    } : value == GrowthArea.other ? {
        other: null
    } : value == GrowthArea.mindset ? {
        mindset: null
    } : value == GrowthArea.career ? {
        career: null
    } : value == GrowthArea.relationships ? {
        relationships: null
    } : value == GrowthArea.health ? {
        health: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalCategory): {
    relationship: null;
} | {
    spiritual: null;
} | {
    travel: null;
} | {
    personalGrowth: null;
} | {
    career: null;
} | {
    financial: null;
} | {
    health: null;
} {
    return value == GoalCategory.relationship ? {
        relationship: null
    } : value == GoalCategory.spiritual ? {
        spiritual: null
    } : value == GoalCategory.travel ? {
        travel: null
    } : value == GoalCategory.personalGrowth ? {
        personalGrowth: null
    } : value == GoalCategory.career ? {
        career: null
    } : value == GoalCategory.financial ? {
        financial: null
    } : value == GoalCategory.health ? {
        health: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmotionTag): {
    sad: null;
} | {
    fearful: null;
} | {
    content: null;
} | {
    anxious: null;
} | {
    happy: null;
} | {
    angry: null;
} | {
    disappointed: null;
} | {
    calm: null;
} | {
    grateful: null;
} | {
    peaceful: null;
} | {
    overwhelmed: null;
} | {
    motivated: null;
} | {
    frustrated: null;
} | {
    excited: null;
} | {
    optimistic: null;
} {
    return value == EmotionTag.sad ? {
        sad: null
    } : value == EmotionTag.fearful ? {
        fearful: null
    } : value == EmotionTag.content ? {
        content: null
    } : value == EmotionTag.anxious ? {
        anxious: null
    } : value == EmotionTag.happy ? {
        happy: null
    } : value == EmotionTag.angry ? {
        angry: null
    } : value == EmotionTag.disappointed ? {
        disappointed: null
    } : value == EmotionTag.calm ? {
        calm: null
    } : value == EmotionTag.grateful ? {
        grateful: null
    } : value == EmotionTag.peaceful ? {
        peaceful: null
    } : value == EmotionTag.overwhelmed ? {
        overwhelmed: null
    } : value == EmotionTag.motivated ? {
        motivated: null
    } : value == EmotionTag.frustrated ? {
        frustrated: null
    } : value == EmotionTag.excited ? {
        excited: null
    } : value == EmotionTag.optimistic ? {
        optimistic: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
