/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Task = IDL.Record({
  'description' : IDL.Text,
  'isComplete' : IDL.Bool,
});
export const ScheduleItem = IDL.Record({
  'timeBlock' : IDL.Text,
  'activity' : IDL.Text,
});
export const DailyPlannerEntry = IDL.Record({
  'waterIntake' : IDL.Nat,
  'date' : IDL.Int,
  'gratitudeEntries' : IDL.Vec(IDL.Text),
  'topTasks' : IDL.Vec(Task),
  'journalEntry' : IDL.Text,
  'notes' : IDL.Text,
  'moodEmoji' : IDL.Text,
  'schedule' : IDL.Vec(ScheduleItem),
});
export const GoalCategory = IDL.Variant({
  'relationship' : IDL.Null,
  'spiritual' : IDL.Null,
  'travel' : IDL.Null,
  'personalGrowth' : IDL.Null,
  'career' : IDL.Null,
  'financial' : IDL.Null,
  'health' : IDL.Null,
});
export const VisionBoardEntry = IDL.Record({
  'progressPercentage' : IDL.Nat,
  'targetYear' : IDL.Int,
  'category' : GoalCategory,
  'whyThisMatters' : IDL.Text,
  'milestones' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Couple = IDL.Record({
  'partner1' : IDL.Principal,
  'partner2' : IDL.Principal,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'name' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDailyPlannerEntry' : IDL.Func([DailyPlannerEntry], [], []),
  'addVisionBoardEntry' : IDL.Func([VisionBoardEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCouple' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
  'deleteDailyPlannerEntry' : IDL.Func([IDL.Int], [], []),
  'deleteVisionBoardEntry' : IDL.Func([IDL.Int], [], []),
  'getAllCouples' : IDL.Func([], [IDL.Vec(Couple)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCouple' : IDL.Func([IDL.Principal], [IDL.Opt(Couple)], ['query']),
  'getDailyPlannerEntries' : IDL.Func(
      [],
      [IDL.Vec(DailyPlannerEntry)],
      ['query'],
    ),
  'getDailyQuote' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisionBoardEntries' : IDL.Func(
      [],
      [IDL.Vec(VisionBoardEntry)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateVisionBoardProgress' : IDL.Func([IDL.Int, IDL.Nat], [], []),
  'updateWaterIntake' : IDL.Func([IDL.Int, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Task = IDL.Record({
    'description' : IDL.Text,
    'isComplete' : IDL.Bool,
  });
  const ScheduleItem = IDL.Record({
    'timeBlock' : IDL.Text,
    'activity' : IDL.Text,
  });
  const DailyPlannerEntry = IDL.Record({
    'waterIntake' : IDL.Nat,
    'date' : IDL.Int,
    'gratitudeEntries' : IDL.Vec(IDL.Text),
    'topTasks' : IDL.Vec(Task),
    'journalEntry' : IDL.Text,
    'notes' : IDL.Text,
    'moodEmoji' : IDL.Text,
    'schedule' : IDL.Vec(ScheduleItem),
  });
  const GoalCategory = IDL.Variant({
    'relationship' : IDL.Null,
    'spiritual' : IDL.Null,
    'travel' : IDL.Null,
    'personalGrowth' : IDL.Null,
    'career' : IDL.Null,
    'financial' : IDL.Null,
    'health' : IDL.Null,
  });
  const VisionBoardEntry = IDL.Record({
    'progressPercentage' : IDL.Nat,
    'targetYear' : IDL.Int,
    'category' : GoalCategory,
    'whyThisMatters' : IDL.Text,
    'milestones' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Couple = IDL.Record({
    'partner1' : IDL.Principal,
    'partner2' : IDL.Principal,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'name' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDailyPlannerEntry' : IDL.Func([DailyPlannerEntry], [], []),
    'addVisionBoardEntry' : IDL.Func([VisionBoardEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCouple' : IDL.Func([IDL.Principal, IDL.Principal], [], []),
    'deleteDailyPlannerEntry' : IDL.Func([IDL.Int], [], []),
    'deleteVisionBoardEntry' : IDL.Func([IDL.Int], [], []),
    'getAllCouples' : IDL.Func([], [IDL.Vec(Couple)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCouple' : IDL.Func([IDL.Principal], [IDL.Opt(Couple)], ['query']),
    'getDailyPlannerEntries' : IDL.Func(
        [],
        [IDL.Vec(DailyPlannerEntry)],
        ['query'],
      ),
    'getDailyQuote' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisionBoardEntries' : IDL.Func(
        [],
        [IDL.Vec(VisionBoardEntry)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateVisionBoardProgress' : IDL.Func([IDL.Int, IDL.Nat], [], []),
    'updateWaterIntake' : IDL.Func([IDL.Int, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };