/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Couple { 'partner1' : Principal, 'partner2' : Principal }
export interface DailyPlannerEntry {
  'waterIntake' : bigint,
  'date' : bigint,
  'gratitudeEntries' : Array<string>,
  'topTasks' : Array<Task>,
  'journalEntry' : string,
  'notes' : string,
  'moodEmoji' : string,
  'schedule' : Array<ScheduleItem>,
}
export type GoalCategory = { 'relationship' : null } |
  { 'spiritual' : null } |
  { 'travel' : null } |
  { 'personalGrowth' : null } |
  { 'career' : null } |
  { 'financial' : null } |
  { 'health' : null };
export interface ScheduleItem { 'timeBlock' : string, 'activity' : string }
export interface Task { 'description' : string, 'isComplete' : boolean }
export interface UserProfile { 'displayName' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VisionBoardEntry {
  'progressPercentage' : bigint,
  'targetYear' : bigint,
  'category' : GoalCategory,
  'whyThisMatters' : string,
  'milestones' : Array<string>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDailyPlannerEntry' : ActorMethod<[DailyPlannerEntry], undefined>,
  'addVisionBoardEntry' : ActorMethod<[VisionBoardEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCouple' : ActorMethod<[Principal, Principal], undefined>,
  'deleteDailyPlannerEntry' : ActorMethod<[bigint], undefined>,
  'deleteVisionBoardEntry' : ActorMethod<[bigint], undefined>,
  'getAllCouples' : ActorMethod<[], Array<Couple>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCouple' : ActorMethod<[Principal], [] | [Couple]>,
  'getDailyPlannerEntries' : ActorMethod<[], Array<DailyPlannerEntry>>,
  'getDailyQuote' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisionBoardEntries' : ActorMethod<[], Array<VisionBoardEntry>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateVisionBoardProgress' : ActorMethod<[bigint, bigint], undefined>,
  'updateWaterIntake' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];